Hellhole/Hellhole.WebUI/Controllers/ParticipationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hellhole.WebUI.Data;
using Microsoft.AspNetCore.Authorization;

namespace Hellhole.WebUI.Controllers
{
    [Authorize]
    public class ParticipationsController : Controller
    {
        private readonly HellholeDbContext _context;

        public ParticipationsController(HellholeDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Get the list of all participations in database
        /// </summary>
        /// <returns>The view that displays all the participations</returns>
        // GET: Participations
        public async Task<IActionResult> Index()
        {
            if (_context.Bands == null || _context.Events == null || _context.Participations == null)
                return View();

            var hellholeDbContext = _context.Participations.Include(p => p.Band).Include(p => p.Event);
            return View(await hellholeDbContext.ToListAsync());
        }

        /// <summary>
        /// GET the detail of a participation with its given concatenated key thanks to Razor page
        /// </summary>
        /// <param name="eventid">The id of the event attached to the participation</param>
        /// <param name="bandid">The id of the event attached to the participation</param>
        /// <returns>The view that displays the detail of the participation</returns>
        // GET: Participations/Details/6/9
        [Route("/Participations/Details/{eventid?}/{bandid?}")]
        public async Task<IActionResult> Details(int? eventid, int? bandid)
        {
            if (_context.Bands == null || _context.Events == null || _context.Participations == null)
                return View();

            if (eventid == null || bandid == null)
            {
                return NotFound();
            }

            var participation = await _context.Participations
                .Include(p => p.Band)
                .Include(p => p.Event)
                .SingleOrDefaultAsync(m => m.EventID == eventid && m.BandID == bandid);
            if (participation == null)
            {
                return NotFound();
            }
            
            return View(participation);
        }

        /// <summary>
        /// GET the view used to create a new participation
        /// </summary>
        /// <returns>The view to create a new participation</returns>
        // GET: Participations/Create
        public IActionResult Create()
        {
            if (_context.Bands == null || _context.Events == null || _context.Participations == null)
                return View();

            ViewData["BandID"] = new SelectList(_context.Bands, "BandID", "Name");
            ViewData["EventID"] = new SelectList(_context.Events.Where(e => !e.Canceled), "EventID", "Title");
            return View();
        }

        /// <summary>
        /// Creates a new participation
        /// </summary>
        /// <param name="participation">the new participation to create</param>
        /// <returns>Redirection to index if succeeded or else the Create view with error messages </returns>
        // POST: Participations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("EventID,BandID,Starting,Ending,Canceled")] Participation participation)
        {
            if (_context.Bands == null || _context.Events == null || _context.Participations == null)
                return View();

            if (ModelState.IsValid)
            {
                Event ev = await _context.Events.SingleOrDefaultAsync(e => e.EventID == participation.EventID);
                if (ev == null || ev.Canceled)
                    ModelState.AddModelError(string.Empty, "You cannot create a participation to a canceled event.");
                if (ev.Type == "Party")
                    ModelState.AddModelError(string.Empty, "You cannot create a participation to a party.");
                if (participation.Starting.CompareTo(ev.Doors) < 0 || participation.Starting.CompareTo(ev.Curfew) > 0)
                    ModelState.AddModelError(string.Empty, "You cannot create a participation that starts before/after its event.");
                if (participation.Ending.CompareTo(ev.Curfew) > 0 || participation.Ending.CompareTo(ev.Doors) < 0)
                    ModelState.AddModelError(string.Empty, "You cannot create a participation that ends before/after its event's doors/curfew.");
                if (participation.Canceled)
                    ModelState.AddModelError(string.Empty, "You can't create a canceled participation.");
                if (ModelState.IsValid)
                {
                    _context.Add(participation);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["BandID"] = new SelectList(_context.Bands, "BandID", "Name", participation.BandID);
            ViewData["EventID"] = new SelectList(_context.Events.Where(e => !e.Canceled && e.Type.Equals("Concert")), "EventID", "Title", participation.EventID);
            return View(participation);
        }

        /// <summary>
        /// GET the view to edit the participaton with the concatenated key
        /// </summary>
        /// <param name="eventid">The EventID of the editable participation</param>
        /// <param name="bandid">The BandID of the editable participation</param>
        /// <returns>The view to edit the participation</returns>
        // GET: Participations/Edit/6/9
        [Route("/Participations/Edit/{eventid?}/{bandid?}")]
        public async Task<IActionResult> Edit(int? eventid, int? bandid)
        {
            if (_context.Bands == null || _context.Events == null || _context.Participations == null)
                return View();

            if (eventid == null || bandid == null)
            {
                return NotFound();
            }

            var participation = await _context.Participations.SingleOrDefaultAsync(m => m.EventID == eventid && m.BandID == bandid);
            if (participation == null)
            { 
                return NotFound();
            }
            ViewData["BandID"] = new SelectList(_context.Bands, "BandID", "Name", participation.BandID);
            ViewData["EventID"] = new SelectList(_context.Events.Where(e => !e.Canceled && e.Type.Equals("Concert")), "EventID", "Title", participation.EventID);
            return View(participation);
        }

        /// <summary>
        /// Edit the participation and redirect to index if succeeded
        /// </summary>
        /// <param name="eventid">The EventID of the participation to edit</param>
        /// <param name="bandid">The BandID of the participation to edit</param>
        /// <param name="participation">The participation to edit </param>
        /// <returns>Redirect to the index if succeeded or else the Edit view with validation errors</returns>
        // POST: Participations/Edit/5/2
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("/Participations/Edit/{eventid}/{bandid}")]
        public async Task<IActionResult> Edit(int eventid, int bandid, [Bind("EventID,BandID,Starting,Ending,Canceled")] Participation participation)
        {
            if (_context.Bands == null || _context.Events == null || _context.Participations == null)
                return View();

            if (eventid != participation.EventID && bandid != participation.BandID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Event ev = await _context.Events.SingleOrDefaultAsync(e => e.EventID == participation.EventID);
                if (participation.Starting.CompareTo(ev.Doors) < 0)
                    ModelState.AddModelError("Starting", "You cannot modify a participation that starts before its event.");
                else if (participation.Ending.CompareTo(ev.Curfew) > 0)
                    ModelState.AddModelError("Ending", "You cannot modify a participation that ends after its event.");
                else
                {
                    try
                    {
                        _context.Update(participation);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ParticipationExists(participation.EventID, participation.BandID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                
            }
            ViewData["BandID"] = new SelectList(_context.Bands, "BandID", "Name", participation.BandID);
            ViewData["EventID"] = new SelectList(_context.Events.Where(e => !e.Canceled && e.Type.Equals("Concert")), "EventID", "Title", participation.EventID);
            return View(participation);
        }

        /// <summary>
        /// GET the view to delete the participation with concatenated key in parameters
        /// </summary>
        /// <param name="eventid">The EventID of the participation to delete</param>
        /// <param name="bandid">The BandID of the participation to delete</param>

Hellhole/Hellhole.WebUI/Views/Participations/Create.cshtml
@model Hellhole.WebUI.Data.Participation

@{
    ViewData["Title"] = "Create new participation";
}

<h2>Create new participation</h2>

<h4>Participation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Participations" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventID" class="control-label"></label>
                <select asp-for="EventID" class ="form-control" asp-items="ViewBag.EventID"></select>
            </div>
            <div class="form-group">
                <label asp-for="BandID" class="control-label"></label>
                <select asp-for="BandID" class ="form-control" asp-items="ViewBag.BandID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Starting" class="control-label"></label>
                <input asp-for="Starting" class="form-control" />
                <span asp-validation-for="Starting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ending" class="control-label"></label>
                <input asp-for="Ending" class="form-control" />
                <span asp-validation-for="Ending" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Canceled" /> @Html.DisplayNameFor(model => model.Canceled)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hellhole/Hellhole.WebUI/Views/Participations/Delete.cshtml
@model Hellhole.WebUI.Data.Participation

@{
    ViewData["Title"] = "Delete participation";
}

<h2>Delete participation</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Participation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Starting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Starting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ending)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ending)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Canceled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Canceled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Band)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Band.BandID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Event.EventID)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-controller="Participations" method="post">
        <input type="hidden" asp-for="EventID" />
        <input type="hidden" asp-for="BandID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hellhole/Hellhole.WebUI/Views/Participations/Details.cshtml
@model Hellhole.WebUI.Data.Participation

@{
    ViewData["Title"] = "Participation details";
}

<h2>Participation details</h2>

<div>
    <h4>Participation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Starting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Starting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ending)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ending)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Canceled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Canceled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Band)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Band.BandID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Event.EventID)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { eventid = Model.EventID, bandid = Model.BandID }) |
    <a asp-action="Index">Back to List</a>
</div>

Hellhole/Hellhole.WebUI/Views/Participations/Edit.cshtml
@model Hellhole.WebUI.Data.Participation

@{
    ViewData["Title"] = "Edit participation";
}

<h2>Edit participation</h2>

<h4>Participation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Participations" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="EventID" />
            <input type="hidden" asp-for="BandID" />
            <div class="form-group">
                <label asp-for="Starting" class="control-label"></label>
                <input asp-for="Starting" class="form-control" />
                <span asp-validation-for="Starting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ending" class="control-label"></label>
                <input asp-for="Ending" class="form-control" />
                <span asp-validation-for="Ending" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Canceled" /> @Html.DisplayNameFor(model => model.Canceled)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hellhole/Hellhole.WebUI/Views/Participations/Index.cshtml
@model IEnumerable<Hellhole.WebUI.Data.Participation>

@{
    ViewData["Title"] = "List of participations";
}

<h2>List of participations</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-data">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Starting)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ending)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Canceled)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Band)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Starting)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ending)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Canceled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Band.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event.Title)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { eventid=item.EventID, bandid=item.BandID }) |
                @Html.ActionLink("Details", "Details", new { eventid = item.EventID, bandid = item.BandID }) |
                @Html.ActionLink("Delete", "Delete", new { eventid = item.EventID, bandid = item.BandID })
            </td>
        </tr>
}
    </tbody>
</table>