Hellhole/Hellhole.WebUI/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hellhole.WebUI.Data;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Net;
using Newtonsoft.Json;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using Hellhole.WebUI.Models;

namespace Hellhole.WebUI.Controllers 
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly HellholeDbContext _context;
        private readonly IHostingEnvironment _environment;

        private const string picDirectory = "Content\\Events";

        public EventsController(HellholeDbContext context, IHostingEnvironment environment)
        {
            _environment = environment;
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            if (_context.Events == null)
                return View();
            var hellholeDbContext = _context.Events.Include(e => e.Place);
            return View(await hellholeDbContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (_context.Events == null)
                return View();

            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(e => e.Place)
                .SingleOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            if (_context.Events == null)
                return View();

            ViewData["PlaceID"] = new SelectList(_context.Places, "PlaceID", "Street");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("EventID,Doors,Curfew,Title,Price,Type,Style,Description,LinkImage,Canceled,PlaceID")] Event @event, IFormFile image = null)
        {
            if (_context.Events == null)
                return View();

            if (ModelState.IsValid)
            {
                if (image == null || image.Length == 0)
                {
                    ModelState.AddModelError(string.Empty, "Image not uploaded");
                    ViewData["PlaceID"] = new SelectList(_context.Places, "PlaceID", "Street", @event.PlaceID);
                    return View(@event);
                }
                await this.UploadImageToBandAsync(image, @event);
                _context.Add(@event);
                await _context.SaveChangesAsync();
                PushNotification(@event);
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlaceID"] = new SelectList(_context.Places, "PlaceID", "Street", @event.PlaceID);
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (_context.Events == null)
                return View();

            if (id == null)
            {
                return NotFound();
            }

            Event @event = await _context.Events.SingleOrDefaultAsync(m => m.EventID == id);
            ViewBag.OtherType = Event.Concert;
            if (@event.Type.Equals(Event.Concert)) ViewBag.OtherType = Event.Party;

            if (@event == null)
            {
                return NotFound();
            }
            ViewData["PlaceID"] = new SelectList(_context.Places, "PlaceID", "Street", @event.PlaceID);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("EventID,Doors,Curfew,Title,Price,Type,Style,Description,LinkImage,Canceled,PlaceID")] Event @event, IFormFile file = null)
        {
            if (_context.Events == null)
                return View();

            if (id != @event.EventID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //File upload
                    if (file != null && file.Length != 0)
                    {
                        string filename = _environment.WebRootPath + @event.LinkImage,
                            formerExtension = Path.GetExtension(@event.LinkImage),
                            nextExtension = Path.GetExtension(file.FileName),
                            newFilename = filename;

                        if (!formerExtension.Equals(nextExtension))
                        {
                            newFilename = Path.Combine(_environment.WebRootPath, picDirectory, Path.GetFileNameWithoutExtension(filename) + nextExtension);
                            System.IO.File.Move(filename, newFilename);
                        }

                        using (var fileStream = new FileStream(newFilename, FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            @event.LinkImage = "\\" + picDirectory + "\\" + Path.GetFileNameWithoutExtension(@event.LinkImage) + nextExtension;
                        }
                    }

                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlaceID"] = new SelectList(_context.Places, "PlaceID", "Street", @event.PlaceID);
            return View(@event);
        }

        /// <summary>
        /// Checks whether an event exists in the database
        /// </summary>
        /// <param name="id">The id of the event to find</param>
        /// <returns>true if the event exists or else false</returns>
        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventID == id);
        }

        /// <summary>
        /// Uploads the picture of the band and replace the current picture if it already exists
        /// </summary>
        /// <param name="file">The picture to upload</param>
        /// <param name="@event">The event needed</param>
        /// <returns></returns>
        private async Task UploadImageToBandAsync(IFormFile file, Event @event)
        {
            string extension = Path.GetExtension(file.FileName);
            string filename = Path.Combine(picDirectory, Guid.NewGuid().ToString() + extension);
            using (var fileStream = new FileStream(Path.Combine(_environment.WebRootPath, filename), FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
                @event.LinkImage = "\\" + filename;
            }
        }

        //Effectue une requete post à OneSignal 
        //OneSignal envoie une notification à tt les appareils

        /// <summary>
        /// Makes a post request to OneSignal. Onesignal will send a notification to all the smartphones
        /// </summary>
        /// <param name="@event"></param>
        private void PushNotification(Event @event)
        {
            HttpWebRequest request = WebRequest.Create("https://onesignal.com/api/v1/notifications") as HttpWebRequest;
            request.KeepAlive = true;
            request.Method = "POST";
            request.ContentType = "application/json; charset=utf-8";
            request.Headers.Add("authorization", "Basic YjFkNDY5NTQtNGQzMi00ODlkLWEyZmYtYjMwNzllNGJjNGI2");
            JsonSerializer serializer = new JsonSerializer();
            var obj = new
            {
                app_id = "792b1e1e-6a40-43c0-878e-f85d3be5b369",
                headings = new { en = "New Event !" },
                contents = new { en = "Hey ! The event \"" + @event.Title + "\" is upcoming, check the details now!" },
                data = new { id = @event.EventID },
                big_picture = "http://hellhole-admin.azurewebsites.net/" + @event.LinkImage,// à modifier
                included_segments = new string[] { "All" }
            };
            String param = JsonConvert.SerializeObject(obj);
            byte[] byteArray = Encoding.UTF8.GetBytes(param);
            string responseContent = null;
            try
            {
                using (Stream writer = request.GetRequestStream())
                {
                    writer.Write(byteArray, 0, byteArray.Length);
                }
                using (WebResponse response = request.GetResponse() as HttpWebResponse)
                {
                    using (StreamReader reader = new StreamReader(response.GetResponseStream()))
                    {
                        responseContent = reader.ReadToEnd();
                    }
                }
            }
            catch (WebException ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);

Hellhole/Hellhole.WebUI/Views/Events/Create.cshtml
@model Hellhole.WebUI.Data.Event

@{
    ViewData["Title"] = "Create new event";
}

<h2>Create new event</h2>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Events" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Doors" class="control-label"></label>
                <input asp-for="Doors" class="form-control" />
                <span asp-validation-for="Doors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curfew" class="control-label"></label>
                <input asp-for="Curfew" class="form-control" />
                <span asp-validation-for="Curfew" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" id="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <p><label><input asp-for="Type" type="radio" value="Concert" /> Concert</label></p>
                <p><label><input asp-for="Type" type="radio" value="Party" /> Party</label></p>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Style" class="control-label"></label>
                <input asp-for="Style" class="form-control" />
                <span asp-validation-for="Style" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="file" class="control-label"></label>
                <input type="file" name="image" class="form-control" accept="image/*"/>
                <input type="hidden" asp-for="LinkImage" value="foo" />
                <span asp-validation-for="LinkImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Canceled" /> @Html.DisplayNameFor(model => model.Canceled)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PlaceID" class="control-label"></label>
                <select asp-for="PlaceID" class ="form-control" asp-items="ViewBag.PlaceID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hellhole/Hellhole.WebUI/Views/Events/Details.cshtml
@model Hellhole.WebUI.Data.Event

@{
    ViewData["Title"] = "Event details";
}

<h2>Event details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Doors)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Doors)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Curfew)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Curfew)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LinkImage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LinkImage)
            <img alt="Picture of event @Model.Title" class="hel-image" src="@Model.LinkImage" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Canceled)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Canceled)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Model.Place.ToString()
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Hellhole/Hellhole.WebUI/Views/Events/Edit.cshtml
@model Hellhole.WebUI.Data.Event

@{
    ViewData["Title"] = "Edit event";
}

<h2>Edit event</h2>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Events" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="EventID" />
            <div class="form-group">
                <label asp-for="Doors" class="control-label"></label>
                <input asp-for="Doors" class="form-control" />
                <span asp-validation-for="Doors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Curfew" class="control-label"></label>
                <input asp-for="Curfew" class="form-control" />
                <span asp-validation-for="Curfew" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label id="Price" asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <p><label><input asp-for="Type" type="radio" value="@Model.Type" /> @Model.Type</label></p>
                <p><label><input asp-for="Type" type="radio" value="@ViewBag.OtherType" /> @ViewBag.OtherType</label></p>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Style" class="control-label"></label>
                <input asp-for="Style" class="form-control" />
                <span asp-validation-for="Style" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="file" class="control-label">Image : </label>
                <input type="file" name="file" class="form-control" accept="image/*" />
                <br />
                <p><img alt="Picture of event @Model.Title" class="hel-image" src="@Model.LinkImage"/></p>
                <input type="hidden" asp-for="LinkImage" value="@Model.LinkImage" />
                <span asp-validation-for="LinkImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Canceled" /> @Html.DisplayNameFor(model => model.Canceled)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="PlaceID" class="control-label"></label>
                <select asp-for="PlaceID" class="form-control" asp-items="ViewBag.PlaceID"></select>
                <span asp-validation-for="PlaceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hellhole/Hellhole.WebUI/Views/Events/Index.cshtml
@model IEnumerable<Hellhole.WebUI.Data.Event>

@{
    ViewData["Title"] = "List of events";
}

<h2>List of events</h2>

<p>
    <a asp-action="Create">Create new event </a>
</p>
<table class="table table-data">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Doors)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Curfew)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Style)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LinkImage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Canceled)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Doors)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Curfew)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Style)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LinkImage)
                <img alt="Picture of event @item.Title" class="hel-image" src="@item.LinkImage" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Canceled)
            </td>
            <td>
              @item.Place.ToString()
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EventID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EventID">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>