Hellhole/Hellhole.WebUI/Controllers/BandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hellhole.WebUI.Data;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace Hellhole.WebUI.Controllers
{
    [Authorize]
    public class BandsController : Controller
    {
        private readonly HellholeDbContext _context;
        private IHostingEnvironment _environment;

        private const string picDirectory = "Content\\Bands";

        public BandsController(HellholeDbContext context, IHostingEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        /// <summary>
        /// GET the index view of bands
        /// </summary>
        /// <returns>The Index view of all bands</returns>
        // GET: Bands
        public async Task<IActionResult> Index()
        {
            if (_context.Bands == null)
                return View();
            return View(await _context.Bands.ToListAsync());
        }

        /// <summary>
        /// GET the details view of a band with its ID
        /// </summary>
        /// <param name="id">The BandID of the band</param>
        /// <returns>The details view of the band</returns>
        // GET: Bands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (_context.Bands == null)
                return View();

            if (id == null)
            {
                return NotFound();
            }

            var band = await _context.Bands
                .SingleOrDefaultAsync(m => m.BandID == id);
            if (band == null)
            {
                return NotFound();
            }

            return View(band);
        }

        /// <summary>
        /// GET the view to create a new band
        /// </summary>
        /// <returns>The view to create a new band</returns>
        // GET: Bands/Create
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Creates a new band and redirect to index
        /// </summary>
        /// <param name="band">The band to create</param>
        /// <param name="image">The image file to insert in WebRoot</param>
        /// <returns>The index vieuw if succeeded or else the create view with validation errors</returns>
        // POST: Bands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BandID,Name,Style,LinkImage,Origin,LinkSpotify,LinkSoundCloud,LinkFacebook, LinkYoutube, LinkBandcamp ,Description")] Band band, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image == null || image.Length == 0)
                {
                    ModelState.AddModelError(string.Empty, "Image not uploaded");
                    return View(band);
                }
                await this.UploadImageToBandAsync(image, band);

                _context.Add(band);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(band);
        }

        /// <summary>
        /// Get the view to edit a band
        /// </summary>
        /// <param name="id">The id of the band to edit</param>
        /// <returns>The view to edit a band</returns>
        // GET: Bands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (_context.Bands == null)
                return View();

            if (id == null)
            {
                return NotFound();
            }

            var band = await _context.Bands.SingleOrDefaultAsync(m => m.BandID == id);
            if (band == null)
            {
                return NotFound();
            }
            return View(band);
        }

        /// <summary>
        /// Edits the band with its ID
        /// </summary>
        /// <param name="id">The ID of the band</param>
        /// <param name="band">The band to edit</param>
        /// <param name="file">The file to insert in webRoot</param>
        /// <returns>The index view if succeeded or else the edit view with validation errors</returns>
        // POST: Bands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BandID,Name,Style,LinkImage,Origin,LinkSpotify,LinkSoundCloud,LinkFacebook, LinkYoutube, LinkBandcamp ,Description")] Band band, IFormFile file = null)
        {
            if (id != band.BandID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //File upload
                    if (file != null && file.Length != 0)
                    {
                        string filename = _environment.WebRootPath + band.LinkImage,
                            formerExtension = Path.GetExtension(band.LinkImage),
                            nextExtension = Path.GetExtension(file.FileName),
                            newFilename = filename;

                        if (!formerExtension.Equals(nextExtension))
                        {
                            newFilename = Path.Combine(_environment.WebRootPath, picDirectory, Path.GetFileNameWithoutExtension(filename) + nextExtension);
                            System.IO.File.Move(filename, newFilename);
                        }
                        //string newFilename = Path.GetFileNameWithoutExtension(filename) + Path.GetExtension(file.FileName);

                        using (var fileStream = new FileStream(newFilename, FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            band.LinkImage = "\\" + picDirectory + "\\" + Path.GetFileNameWithoutExtension(band.LinkImage) + nextExtension;
                        }
                    }
                    _context.Update(band);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BandExists(band.BandID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(band);
        }

        /// <summary>
        /// Uploads a file to webRoot and replace if already exists
        /// </summary>
        /// <param name="file">The file to upload</param>
        /// <param name="band">The band thats owns the file</param>
        /// <returns></returns>
        private async Task UploadImageToBandAsync(IFormFile file, Band band)
        {
            string extension = Path.GetExtension(file.FileName);
            string filename = Path.Combine(picDirectory, Guid.NewGuid().ToString() + extension);
            using (var fileStream = new FileStream(Path.Combine(_environment.WebRootPath, filename), FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
                band.LinkImage = "\\" + filename;
            }
        }
        /// <summary>
        /// Checks whether a band exsists or not
        /// </summary>
        /// <param name="id">The id of the band to check</param>
        /// <returns>True if the band exists or else false</returns>
        private bool BandExists(int id)
        {
            return _context.Bands.Any(e => e.BandID == id);
        }
    }
}

Hellhole/Hellhole.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hellhole.WebUI.Models;
using Microsoft.AspNetCore.Authorization;

namespace Hellhole.WebUI.Controllers
{ 
    [Authorize]
    public class HomeController : Controller
    {
        /// <summary>
        /// Get the Index View
        /// </summary>
        /// <returns>The index view</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Get the About view
        /// </summary>
        /// <returns>The about view</returns>
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        /// <summary>
        /// Gets the Contact page
        /// </summary>
        /// <returns>The contact view</returns>
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        /// <summary>
        /// Gets the songs chat view in order to choose the song you want
        /// </summary>
        /// <returns>The songs chat view</returns>
        public IActionResult Songs()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Error()
        {
            if (Activity.Current == null)
                return null;
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hellhole/Hellhole.WebUI/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hellhole.WebUI.Data;
using Microsoft.AspNetCore.Authorization;
using System.Text;
using System.Net.Http;
using Hellhole.WebUI.Models;
using Newtonsoft.Json;

namespace Hellhole.WebUI.Controllers
{
    [Authorize]
    public class PlacesController : Controller
    {
        private readonly HellholeDbContext _context;

        public PlacesController(HellholeDbContext context)
        {
            _context = context;
        }

        // GET: Places

        /// <summary>
        /// Get the view to see all the places of the application
        /// </summary>
        /// <returns>the view required</returns>
        public async Task<IActionResult> Index()
        {
            if (_context.Places == null)
                return View();

            return View(await _context.Places.ToListAsync());
        }

        // GET: Places/Create

        /// <summary>
        /// Get the view to create a place
        /// </summary>
        /// <returns>The view required</returns>
        public IActionResult Create()
        {
            return View();
        }

        // POST: Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        /// <summary>
        /// Creates a new place
        /// </summary>
        /// <param name="placeParam">The place that will be created</param>
        /// <returns>Redirect to Index if succeeded or else send the error messages</returns>
        [HttpPost]
        public async Task<IActionResult> Create([Bind("PlaceID,PostalCode,City,Street,Number,Commune,Mailbox")] Place placeParam = null)
        {
            if (placeParam != null && ModelState.IsValid)
            {

                if(! await CheckExistsAsync(placeParam))
                {
                    ModelState.AddModelError(string.Empty, "The place doesn't exists.");
                    return View(placeParam);
                }

                _context.Add(placeParam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(placeParam);
        }

        // GET: Places/Details/5

        /// <summary>
        /// Get the details of a place 
        /// </summary>
        /// <param name="id">The id of the place to find</param>
        /// <returns>The view of the place if found or else the NotFound page</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (_context.Places == null)
                return View();

            if (id == null)
            {
                return NotFound();
            }

            var place = await _context.Places
                .SingleOrDefaultAsync(m => m.PlaceID == id);
            if (place == null)
            {
                return NotFound();
            }

            return View(place);
        }

        // GET: Places/Edit/5

        /// <summary>
        /// Get the page to edit a place
        /// </summary>
        /// <param name="id">The PlaceID of the place to edit</param>
        /// <returns>NotFound page if not found or else the view required</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var place = await _context.Places.SingleOrDefaultAsync(m => m.PlaceID == id);
            if (place == null)
            {
                return NotFound();
            }
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        /// <summary>
        /// Edits the place
        /// </summary>
        /// <param name="id">the id of the place to edit</param>
        /// <param name="place">The new values of the place to edit</param>
        /// <returns>Redirect to Index if succeeded, or else send the error messages</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("PlaceID,PostalCode,City,Street,Number,Commune,Mailbox")] Place place)
        {
            if (id != place.PlaceID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                if (!await CheckExistsAsync(place))
                {
                    ModelState.AddModelError(string.Empty, "The place doesn't exists.");
                    return View(place);
                }

                try
                {
                    _context.Update(place);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaceExists(place.PlaceID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(place);
        }

        /// <summary>
        /// Checks whether the place really exists thanks to Google maps
        /// </summary>
        /// <param name="place">the place to check</param>
        /// <returns>true if the place exists or else false</returns>
        private async Task<bool> CheckExistsAsync(Place place)
        {
            string adr = place.PostalCode + "," + place.Street + "," + place.Number + "," + place.Commune + "," + place.City,
                cle = "AIzaSyDrkgUtF_6SwhhQnv5T6ryq2eRdSDgyGe0";

            StringBuilder builder = new StringBuilder(adr);
            builder.Replace(' ', '+');
            using (var client = new HttpClient())
            {
                try
                {
                    client.BaseAddress = new Uri("https://maps.googleapis.com");
                    var response = await client.GetAsync($"/maps/api/geocode/json?address={builder.ToString()}&key={cle}");
                    response.EnsureSuccessStatusCode();
                    var stringResult = await response.Content.ReadAsStringAsync();
                    GeocoMapsResponse rawWeather = JsonConvert.DeserializeObject<GeocoMapsResponse>(stringResult);
                    return rawWeather.Status.Equals(GeocoMapsResponse.OK_CODE);
                }
                catch (HttpRequestException httpRequestException)
                {
                    return false;
                }
            }
        }

        /// <summary>
        /// Checks whether the place exists in the database
        /// </summary>
        /// <param name="id">The placeID to check</param>
        /// <returns></returns>
        private bool PlaceExists(int id)
        {
            return _context.Places.Any(e => e.PlaceID == id);
        }
    }
}

Hellhole/Hellhole.WebUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Hellhole/Hellhole.WebUI/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hellhole/Hellhole.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Welcome to Index !</h1>

Hellhole/Hellhole.WebUI/Views/Home/Songs.cshtml
@{
    ViewData["Title"] = "Songs";
    Layout = "~/Views/Home/_LayoutSongs.cshtml";
}
<div class="row">
    <div class="col-md-12">

    </div>
</div>
<h2>Songs</h2>

<div class="row">
    <div class="col-md-12">
        <table id="song-table" class="table table-striped">
            <thead>
                <tr>
                    <th>Artiste</th>
                    <th>Titre</th>
                    <th>Likes</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="song in songs">
                    <td> {{ song.artiste }}</td>
                    <td> {{ song.titre }}</td>
                    <td> {{ song.like }}</td>
                    <td>
                        <button v-if="liked && song.artiste + '_' + song.titre == liked" class="btn btn-warning" v-on:click="unlike(song)">Unlike</button>
                        <button v-else class="btn btn-info" v-on:click="like(song)">Like</button>
                    </td>
                    <td>
                        <button class="btn btn-danger" v-on:click="remove(song)">Remove</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div id="song-form">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="artiste">Artiste :</label>
                <input type="text" v-model="song.artiste" class="form-control" name="artiste">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="titre">Titre:</label>
                <input type="text" v-model="song.titre" name="titre" class="form-control">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button id="send-song" v-on:click="send()" class="btn btn-primary">Send</button>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <button id="reset-songs" v-on:click="reset()" class="btn btn-danger">Reset songs</button>
        </div>
    </div>
</div>

Hellhole/Hellhole.WebUI/Views/Home/_LayoutSongs.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hellhole.WebUI</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" type="text/css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Hellhole Admin</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Places" asp-action="Index">Places</a></li>
                    <li><a asp-controller="Events" asp-action="Index">Events</a></li>
                    <li><a asp-controller="Bands" asp-action="Index">Bands</a></li>
                    <li><a asp-controller="Participations" asp-action="Index">Participations</a></li>
                    <li><a asp-controller="Home" asp-action="Songs">Songs chat</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Hellhole Admin</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>
    <script type="text/javascript">
        if (typeof Promise === 'undefined') {
            document.write('<script type="text/javascript" src="/lib/signalR/signalr-clientES5-1.0.0-alpha2-final.min.js"><\/script>');
        }
        else {
            document.write('<script type="text/javascript" src="/lib/signalR/signalr-client-1.0.0-alpha2-final.min.js"><\/script>');
        }
    </script>
    <script type="text/javascript" src="~/lib/toastr/toastr.min.js"></script>
    <script type="text/javascript" src="~/lib/vue.min.js"></script>
    <script type="text/javascript" src="~/js/signalVue.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>